<meta charset="utf-8">
<?php echo $this->headTitle($this->translate('RtK - Administration'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php
echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<!-- Le styles -->
<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
        ->appendStylesheet($this->basePath('/css/Backend/bootstrap.css'))
        ->appendStylesheet($this->basePath('/css/Backend/style.css'))
        ->appendStylesheet($this->basePath('/css/Backend/jquery-ui.css'))
        ->appendStylesheet($this->basePath('/css/Backend/AdminLTE.css'))
        ->appendStylesheet($this->basePath('/css/Backend/skin-blue.css'))
        ->appendStylesheet($this->basePath('/css/wow.css'))
?>

<!-- Scripts -->
<?php
echo $this->headScript()
        ->appendFile($this->basePath('js/jquery.min.js'))
        ->appendFile($this->basePath('js/jquery/jquery-ui.min.js'))
        ->appendFile($this->basePath('js/bootstrap.min.js'))
        ->appendFile($this->basePath('js/commun.js'))
        ->appendFile($this->basePath('js/backend.js'))
        ->appendFile($this->basePath('js/jquery/validate/jquery.validate.min.js'))
        ->appendFile($this->basePath('js/jquery/validate/messages_fr.min.js'))
        ->appendFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->basePath('js/jquery.dataTables.min.js'))
        ->appendFile($this->basePath('js/zf-table.js'))
        ->appendFile($this->basePath('js/DT_bootstrap_3.js'))
        ->appendFile($this->basePath('js/plugins/slimScroll/jquery.slimscroll.min.js'))
        ->appendFile($this->basePath('js/plugins/fastclick/fastclick.js'))
        ->appendFile($this->basePath('js/app.min.js'))
;
?>