<a href="<?php echo $this->url('home'); ?>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>R</b>TK</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Raid</b>Tracker</span>
</a>
<nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">    
            <div id='login'>
            <?php if(!$this->zfcUserIdentity()): ?>
                <?php echo $this->zfcUserLoginWidget(array('redirect'=>'home')); ?>
                <a href="<?php echo $this->url('zfcuser/register'); ?>"><?php echo $this->translate('Créez un compte! ') ?></a>
            <?php else: ?>
           
        </div>
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle"  arial-expended="false" data-toggle="dropdown">
              <span class="hidden-xs"><?php echo $this->zfcUserIdentity()->getDisplayname(); ?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat"><?php echo $this->translate('Profil') ?></a>
                </div>
                <div class="pull-right">
                  <a href="<?php echo $this->url('zfcuser/logout'); ?>" class="btn btn-default btn-flat"><?php echo $this->translate('Déconnexion') ?></a>
                </div>
              </li>
            </ul>
          </li>
            <?php endif?>
        </ul>
      </div>
    </nav>

