<div>
    <label>
        <?php echo $this->translate('Locale') ?>
    </label>
</div>
<div class="form-group">
    <select name="locale">
        <option value="fr_FR"><?php echo $this->translate('Français') ?></option>
        <option value="en_GB"><?php echo $this->translate('Anglais') ?></option>
        <option value="es_ES"><?php echo $this->translate('Espagnole') ?></option>
        <option value="ru_RU"><?php echo $this->translate('Russe') ?></option>
        <option value="de_DE"><?php echo $this->translate('Allemand') ?></option>
        <option value="pt_PT"><?php echo $this->translate('Portugais') ?></option>
        <option value="it_IT"><?php echo $this->translate('Italien') ?></option>
    </select>
</div>