<?php echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5); ?>
<html lang="fr">
    <head>
        <?= $this->render('layout/backend/head') ?>
    </head>
    <body class="hold-transition skin-blue fixed sidebar-mini">
        <div id="loading">
            <div class="center">
                <div class="circle"></div>
                <div class="circle1"></div>
            </div>
        </div>
        <div class="wrapper">
            <header class="main-header">
                <?php echo $this->render('layout/backend/header') ?>            
            </header>
            
            <aside class="main-sidebar">
<!--             sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
<!--               Sidebar Menu             -->
                    <ul class="sidebar-menu">
                    <?=
                        $this->navigation('BackendNavigation')->menu()
                        ->setPartial(array('layout/backend/navbar.phtml', 'backend-nav'))
                    ?>
                    </ul>
                </section>
           </aside>
<!--             Main content               -->
            <div class="content-wrapper">
                <section class="content">
                    <div id="msg">
                        <?= $this->render('layout/app/messages') ?>
                    </div>
                
                  <?php echo $this->content ?>
                </section>
            </div>
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    RaidTracker
                </div>
                <p><strong>&copy; 2016 - <?php echo date('Y') ?> by Antarus & Capi </strong><?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
    </body>
</html>
