<?php
$recaptcha = new ZendService\ReCaptcha\ReCaptcha($this->publicKey, $this->privateKey, null, array('lang' => 'fr'));
?>
<h4 class="page-title"><?php echo $this->translate('Nous contacter'); ?></h4>
<section class="col-md-6">
    <form class="form-horizontal form-contact" method="post" action="<?php echo $this->url('contact', array('action' => 'getForm')); ?>">
        <h4 class="form-title"><?php echo $this->translate('Laissez-nous un message'); ?></h4>
        <div class="form-group">
            <label for="inputName">
                <?php echo $this->translate('Nom'); ?>
            </label>
            <input type="text" class="form-control" id="inputName" name="name" >
        </div>
        <div class="form-group">
            <label for="inputEmail">
                <?php echo $this->translate('E-mail*'); ?>
            </label>
            <input type="email" class="form-control" id="inputEmail" name="email" required>
        </div>
        <div class="form-group">
            <label for="inputSubject">
                <?php echo $this->translate('Sujet*'); ?>
            </label>
            <input type="text" class="form-control" id="inputSubject" name="subject" required>
        </div>
        <div class="form-group">
            <label for="textareaMessage">
                <?php echo $this->translate('Comment pouvons-nous vous aider?*'); ?>
            </label> 
            <textarea class="form-control" id="textareaMessage"rows="5" name="message" required>
        
            </textarea>
        </div>
        <div class="form-group">
            <?php echo $recaptcha->getHTML(); ?>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg"><?php echo $this->translate('Envoyer'); ?></button>
        </div>
    </form> 
</section>
<section class="media social col-md-6">
    <h4><?php echo $this->translate('Vous pouvez également nous contacter via'); ?></h4>
    <div class="col-md-4" style="padding-bottom: 7px;">
        <div class="media-left">
            <img class="media-object" src="<?php echo $this->basePath('img/twitter.png'); ?>" alt="logo-twitter" width="50"/>
        </div>
        <div class="media-body">
            <small>Twitter</small><br> 
            <a href="https://twitter.com/RaidTracKer" target="_blank">@RaidTracKer</a>
        </div>
    </div>

    <div class="col-md-4" style="padding-bottom: 7px;">
        <div class="media-left">
            <img class="media-object" src="<?php echo $this->basePath('img/facebook.png'); ?>" alt="logo-facebook" width="40"/> 
        </div>
        <div class="media-body" style="padding-left: 10px;">
            <small>Facebook</small><br> 
            <a href="#">Facebook</a>
        </div>
    </div>

    <div class="col-md-4" style="padding-bottom: 7px;">
        <div class="media-left">
            <img src="<?php echo $this->basePath('img/Discord-Logo-White'); ?>" alt="logo-discord" width="50"/>
        </div>
        <div class="media-body">
            <small>Discord</small><br> 
            <a href="https://discord.gg/A3R2J" target="_blank">RaidTracKer</a>
        </div>
    </div>
</section>