<h4 class="page-title"><?php echo $this->translate('Nous contacter'); ?></h4>
<form class="form-contact col-md-6">
    <h4 class="form-title"><?php echo $this->translate('Laissez-nous un message'); ?></h4>
    <label>
        <?php echo $this->translate('Nom') ; ?>
    </label>
    <input type="text" name="name" width="200">
    <label>
        <?php echo $this->translate('E-mail*') ; ?>
    </label>
    <input type="email" name="email" width="200" required>
    <label>
       <?php echo $this->translate('Sujet*') ; ?>
    </label>
    <input type="text" name="subject" width="200" required>
    <label>
        <?php echo $this->translate('Comment pouvons-nous vous aider?*') ; ?>
    </label> 
    <textarea rows="10" cols="100" name="message" required>
        
    </textarea>
</form> 
