<section class="col-md-11">
    <div class="jumbotron">
        <h1><?php echo $this->translate('Bienvenue sur RaidTracker'); ?></h1>
        <p>
            <?php
            echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipisicing elit, 
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, 
                eaque ipsa quae ab illo inventore');
            ?>
        </p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button"><?php echo $this->translate('En savoir plus'); ?></a></p>
    </div>
    <section>
        <article class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Lorem ipsum</h3>
            </div>
            <div class="panel-body">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
                <p>
                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, 
                    eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam 
                    voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem 
                    sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non 
                    numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis 
                    nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? 
                </p>
            </div>
            <div class="panel-footer">
                <div class="panel-group">
                    <div class="panel-head">
                        <a data-toggle="collapse" href='#collapse1'><h4 class="panel-title">
                                <?php echo $this->translate('Commentaires'); ?>
                                <span class="glyphicon glyphicon-collapse-down pull-right"></span>
                            </h4></a>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse comment">
                        <div class="panel-body">
                            <p> Ici se trouvent les commentaires de la news </p>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    </section>
</section>
<button type="button" class="navbar-toggle widget-toggle" data-toggle="collapse" data-target="#widget-collapse" aria-expanded="false">
    <span class="glyphicon glyphicon-tasks"></span>
</button>
<aside class="widget-container collapse navbar-collapse" id="widget-collapse">
    <div>
        <a class="twitter-timeline" data-width="220" data-height="300" data-theme="dark" data-link-color="#19CF86" href="https://twitter.com/Blizzard_Ent">
            Tweets by Blizzard
        </a> 
        <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
    <div>
        <iframe src="https://discordapp.com/widget?id=224905249108787200&theme=dark" width="220" height="300" allowtransparency="true" frameborder="0"></iframe>
    </div>
</aside>
<script>
    
    $(window).resize(function(){
        if($(window).width() <= 1243){
            console.log($(window).width());
            
        }
    });
    
</script>