<section class="col-md-12">
    <div class="jumbotron">
        <h1><?php echo $this->translate('Bienvenue sur RaidTracker'); ?></h1>
        <p>
            <?php
            echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipisicing elit, 
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, 
                eaque ipsa quae ab illo inventore');
            ?>
        </p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button"><?php echo $this->translate('En savoir plus'); ?></a></p>
    </div>
    <section>

        <?php  foreach($this->listeArticles as $article) : ?>
        <article class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $article['titleArticle'] ;?></h3>
            </div>
            <div class="panel-body">
                <?php echo $article['content'] ; ?>
            </div>
            <div class="panel-footer">
                <?php sprintf($this->translate("Rédigé par %s, mis à jours le %s par %s "),$article['writeBy'],$article['lastUpdate'],$article['updateBy']); ?>
            </div>
        </article>
        <?php endforeach; ?>
    </section>
</section>

