<h1><?php echo $this->translate("Modifier un roster") ?></h1>

<form id="frmAjax" method='post' action="<?php echo $this->url('backend-roster-update', array('id' => $this->id)) ?>" class="form-inline">
    <fieldset>
        <input type="hidden" name="idRoster" required="true" value="<?php echo $this->id; ?>" />
        <div class="control-group">
            <label class="control-label"><?php echo $this->translate("Nom") ?></label>
            <div class="controls">
                <input id="nomRoster" type='text' name="nom" required="true" value="<?php echo $roster['nom']; ?>"/>
            </div>

            <h3><?php echo $this->translate("Liste des joueurs") ?></h3>

            <a id="addPersonnage" href="<?php echo $this->url('backend-roster-has-personnage-add', array('id' => $this->id)) ?>">
                <?php echo $this->translate("Ajouter un joueur au roster") ?></a> | 
            <a id="majPersonnage" href="#">
                <?php echo $this->translate("Met a jour les personnages du roster (ilvl)") ?></a>
            <?php foreach ($roster['roles'] as $role) { ?>
                <h3><?php echo $this->translate($role["nom"]) ?></h3>
                <div id="tableContainer<?php echo $role["idRole"] ?>">
                </div>

                <script>
                    $("#tableContainer<?php echo $role["idRole"] ?>").zfTable("<?php echo $this->url('backend-roster-has-personnage-ajaxList', array('idRole' => $role["idRole"], 'idRoster' => $this->id)); ?> ");
                </script>


                <?php
            }
            if (!isset($roster['roles'])) {
                ?>
                <p>   <?php echo $this->translate("Aucun joueur définit."); ?></p>
                <?php
            }
            ?>
            <div class="form-actions">
                <input id="submit" type='submit' value='submit' class="btn"/>
            </div>
            <div class="import">

            </div>
        </div>
    </fieldset>
</form>
<!-- empty div to save dialog temporary -->
<div id="popupGlobal"></div>


<script type="text/javascript">
    $('#majPersonnage').click(function ()
    {
        $.ajax
                ({
                    url: "<?php echo $this->url('backend-roster-has-personnage-maj', array('id' => $this->id)) ?>",
                    //data: {"book_id": book_id},
                    type: 'post',
                    complete: function (html) {
                        $("#msg").removeClass('alert-success');
                        $("#msg").removeClass('alert-danger');
                        if (html.responseJSON.error) {
                            $("#msg").addClass('alert-danger').text(html.responseJSON.error.msg);
                        } else {
                            $("#msg").addClass('alert-success').text(html.responseJSON.success.msg);
                        }
                    }
                })
    });


    function majListe() {
<?php foreach ($roster['roles'] as $role) { ?>
            $("#tableContainer<?php echo $role["idRole"] ?>").html('');
            $("#tableContainer<?php echo $role["idRole"] ?>").zfTable("<?php echo $this->url('backend-roster-has-personnage-ajaxList', array('idRole' => $role["idRole"], 'idRoster' => $this->id)); ?>");
<?php } ?>
    }
    $(function () {
        initDialogAddPersonnage("<?php echo $this->translate("Ajout d'un joueur au roster") ?> [<?php echo $roster['nom']; ?>]")

    });
</script>
