<a href="<?php echo $this->url('backend-personnages-create'); ?>" class="btn btn-success"><?php echo $this->translate("Créer") ?></a>
<a href="<?php echo $this->url('backend-personnages-import'); ?>" class="btn btn-success"><?php echo $this->translate("Importer") ?></a>
<div id="tableContainer">
</div>

<script>
    $("#tableContainer").zfTable('<?php echo $this->url('backend-personnages-ajaxList'); ?>');
</script>
