<h1><?php echo $this->translate("Création") ?></h1>

<?php
echo $this->partial('partial/form-partial', array(
    'form' => $this->form,
    'url' => $this->url('backend-pallier-afficher-create'))
);
?>

<script type ="text/javascript">

    $(function () {
        autocompleteBase("input[name=roster]", "input[name=idRoster]", "<?php echo $this->url('backend-roster-autocomplete', array('id' => $this->id)) ?>", "roster");
    });

</script>