<h1>Mise à jour</h1>

<?php
echo $this->partial('partial/form-partial', array(
    'form' => $this->form,
    'url' => $this->url('backend-pallier-afficher-update', array('id' => $this->id)))
);
?>
<script type ="text/javascript">

    $(function () {
        autocompleteBase("input[name=mode]", "input[name=idModeDifficulte]", "<?php echo $this->url('backend-mode-autocomplete', array('id' => $this->id)) ?>", "mode");
        autocompleteBase("input[name=zone]", "input[name=idZone]", "<?php echo $this->url('backend-zone-autocomplete', array('id' => $this->id)) ?>", "zone");
        autocompleteBase("input[name=roster]", "input[name=idRoster]", "<?php echo $this->url('backend-roster-autocomplete', array('id' => $this->id)) ?>", "roster");
    });

</script>
