
<?php
$page = $this->page;
$level = empty($this->level) ? 0 : $this->level;
$hasChildren = false;
foreach ($page->getPages() as $child) {
    if ($this->navigation()->accept($child)) {
        $hasChildren = true;
        break;
    }
}
if (!$hasChildren):
    
?>
<!--<li><a href="<?= $page->getHref() ?>"><i class="<?php echo "fa fa-%s" ?>"></i> <span><?= $page->getLabel() ?></span></a></li>-->
    <?php
    
    switch ($page->getLabel()){
        case "Accueil":
            $icone = "home";
            break;
        case "Utilisateurs":
            $icone = "group";
            break;
        case "Evenements":
            $icone = "calendar";
            break;
        default:
            $icone = "anchor";
            break;
    }
    // generate markup
    $markup = sprintf('<li><a href="%s">',$page->getHref());
    $markup .= sprintf('<i class="fa fa-%s"></i> <span>',$icone);
    $markup .= $page->getLabel();
    $markup .= '</span></a></li>';
    echo $markup;
else:
    $liClass = ($level > 0) ? 'dropdown-submenu' : 'dropdown';
    ?>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-link"></i>
            <span><?= $page->getLabel() ?></span>
        </a>
        <ul class="treeview-menu">
            <?php
            foreach ($page->getPages() as $child):
                if (!$this->navigation()->accept($child))
                    continue;
                ?>
                <?= $this->partial('partial/commun/menu-item', array('page' => $child, 'level' => $level + 1)) ?>
            <?php endforeach ?>
        </ul>
    </li>
<?php endif ?>
