
<?php
$page = $this->page;
$level = empty($this->level) ? 0 : $this->level;
$hasChildren = false;
foreach ($page->getPages() as $child) {
    if ($this->navigation()->accept($child)) {
        $hasChildren = true;
        break;
    }
}
if (!$hasChildren):
    
?>
    <?php
    
    switch ($page->getLabel()){
        case "Accueil":
            $icone = "home";
            break;
        case "Npc":
            $icone = "optin-monster";
            break;
        case "Guildes":
            $icone = "users";
            break;
        case "Utilisateurs":
            $icone = "user";
            break;
        case "Evenements":
            $icone = "calendar";
            break;
        case "Roster":
            $icone = "eye";
            break;
        default:
            $icone = "circle-thin";
            break;
    }
    // generate markup
    $markup = sprintf('<li><a href="%s">',$page->getHref());
    $markup .= sprintf('<i class="fa fa-%s"></i> <span>',$icone);
    $markup .= $page->getLabel();
    $markup .= '</span></a></li>';
    echo $markup;
else:
    $liClass = ($level > 0) ? 'dropdown-submenu' : 'dropdown';
    switch ($page->getLabel()){
        case "Personnage":
            $icone = "child";
            break;
        case "Raid":
            $icone = "map-o";
            break;
        default:
            $icone = "circle-thin";
            break;
    }
    // generate markup
    $markup = sprintf('<a href="#"><i class="fa fa-%s"></i> <span>',$icone);

    $markup .= $page->getLabel();
    $markup .= '</span></a>';
    ?>
    <li class="treeview">
        <?php echo $markup ?>
        <ul class="treeview-menu">
            <?php
            foreach ($page->getPages() as $child):
                if (!$this->navigation()->accept($child))
                    continue;
                ?>
                <?= $this->partial('partial/commun/menu-item', array('page' => $child, 'level' => $level + 1)) ?>
            <?php endforeach ?>
        </ul>
    </li>
<?php endif ?>
