<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Frontend\Module' => __DIR__ . '/Module.php',
    'Frontend\Controller\FrontController' => __DIR__ . '/src/Frontend/Controller/FrontController.php',
    'Frontend\Controller\RaidsController' => __DIR__ . '/src/Frontend/Controller/RaidsController.php',
    'Frontend\Controller\RosterController' => __DIR__ . '/src/Frontend/Controller/RosterController.php',
    'Frontend\Grid\RaidsGrid' => __DIR__ . '/src/Frontend/Grid/RaidsGrid.php',
);
