<aside class="control-sidebar control-sidebar-dark" >
    <div class="tab-content">
        <div>
            <a class="twitter-timeline" data-width="220" data-height="300" data-theme="dark" data-link-color="#19CF86" href="https://twitter.com/RaidTracKer">
                Tweets by RaidTracKer
            </a> 
            <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
        <div>
            <iframe src="https://discordapp.com/widget?id=224905249108787200&theme=dark" width="220" height="300" allowtransparency="true" frameborder="0"></iframe>
        </div>
    </div>
</aside>