<header>
    <div class="container">
        <a href="<?php echo $this->url('home'); ?>">
        <h1 class="fontface" id="title">RAID Tracker</h1>
        </a>
        <nav>
            <ul>
                <li><a href="#"><?php echo $this->translate('Encore') ?></a></li>
                <li><a href="#"><?php echo $this->translate('En') ?></a></li>
                <li><a href="#"><?php echo $this->translate('Developpement') ?></a></li>
                <li>
                    <a href="<?php echo $this->url('Contact'); ?>">
                        <?php echo $this->translate('Contact') ?>
                    </a>
                </li>
            </ul>
        </nav>
    </div> 
    
</header>

