<meta charset="utf-8">
<?php echo $this->headTitle($this->translate('Raid-Tracker'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php
echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<!-- Le styles -->
<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
        ->appendStylesheet($this->basePath('css/bootstrap.css'))
        ->appendStylesheet($this->basePath('css/AdminLTE.css'))
        ->appendStylesheet($this->basePath('css/skin-blue.min.css'))
        ->appendStylesheet($this->basePath('css/style-2.css'))
        ->appendStylesheet($this->basePath('plugin/fancybox/source/jquery.fancybox.css?v=2.1.5'))
        ->appendStylesheet("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css")
        ->appendStylesheet("https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css")
        ->appendStylesheet("https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css");

?>

<!-- Scripts -->
<?php
echo $this->headScript()
        ->appendFile($this->basePath('js/jquery.min.js'))
        ->appendFile($this->basePath('js/commun.js'))
        ->appendFile($this->basePath('js/bootstrap.min.js'))
        ->appendFile($this->basePath('js/user/user.js'))
//        ->appendFile($this->basePath('js/jquery/validate/messages_fr.min.js'))
//        ->appendFile($this->basePath('js/jquery/validate/jquery.validate.min.js'))
        ->appendFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
//        ->appendFile($this->basePath('js/jquery.dataTables.min.js'))
        ->appendFile($this->basePath('js/zf-table.js'))
        ->appendFile($this->basePath('plugin/fancybox/source/jquery.fancybox.pack.js?v=2.1.5'))
        ->appendFile("//wow.zamimg.com/widgets/power.js")
        ->appendFile($this->basePath('js/wowhead.js'))
        ->appendFile($this->basePath('js/Chart.js'))
        ->appendFile($this->basePath('js/frontend.js'))
        ->appendFile($this->basePath('js/app.min.js'))
//        ->appendFile($this->basePath('js/DT_bootstrap_3.js'))
;
?>