<header>
    <div class="container">
            <div id="logo">
                <a href="<?php echo $this->url('home'); ?>">
                 <img src="<?php echo $this->basePath('img/Logotype-2.png'); ?>" alt="RTK Logotype"/>
                </a>
            </div>
        <nav>
            <ul>
                <li>
                    <a href="<?php echo $this->url('home'); ?>">
                        <?php echo $this->translate('home') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('apropos'); ?>">
                        <?php echo $this->translate('A propos') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('discordbot'); ?>">
                        <?php echo $this->translate('Discord BOT') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('contact'); ?>">
                        <?php echo $this->translate('Contact') ?>
                    </a>
                </li>
                <li>
                <?php if($this->isAllowed( 'menu', 'menu_admin' )):?>
                    <a href="<?php echo $this->url('backend-index'); ?>">
                        <?php echo $this->translate('Backend') ?>
                    </a>
                <?php endif;?>
                </li>
            </ul>
        </nav>
    
    </div> 
    <div id="border-bg"></div>
</header>

