<?php

use Zend\Mvc\Controller\Plugin\FlashMessenger;

$messenger = $this->flashmessenger(); //->getPluginFlashMessenger();

foreach (array(
FlashMessenger::NAMESPACE_ERROR,
 FlashMessenger::NAMESPACE_SUCCESS,
 FlashMessenger::NAMESPACE_INFO,
 FlashMessenger::NAMESPACE_DEFAULT,
 FlashMessenger::NAMESPACE_WARNING)
as $sNamespace):
    $messenger->setNamespace($sNamespace);
    $aMessages = $messenger->getCurrentMessages();
    //$aMessages = array_merge($messenger->getCurrentMessages(), $messenger->getMessages());
    $messenger->clearCurrentMessages();
    $aClasseCommune = array('alert alert-dismissible');

    echo $messenger->renderAllMessages($sNamespace, $aMessages, $aClasseCommune, true);
endforeach
?>

