<?php

use Zend\Mvc\Controller\Plugin\FlashMessenger;

$messenger = $this->flashmessenger(); //->getPluginFlashMessenger();
$messenger->setMessageOpenFormat('<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
        <h4><i class="icon fa fa-check"></i>Alert!</h4><p>')
        ->setMessageSeparatorString('</p><p>')
        ->setMessageCloseString('</p></div>');
foreach (array(
FlashMessenger::NAMESPACE_ERROR,
 FlashMessenger::NAMESPACE_SUCCESS,
 FlashMessenger::NAMESPACE_INFO,
 FlashMessenger::NAMESPACE_DEFAULT)
as $sNamespace):
    $messenger->setNamespace($sNamespace);
    $aMessages = array_merge($messenger->getCurrentMessages(), $messenger->getMessages());
    $messenger->clearCurrentMessages();
    $aClasseCommune = array();

    switch ($sNamespace) {
        case FlashMessenger::NAMESPACE_ERROR:
            $aClasseCommune[2] = 'alert alert-danger alert-dismissible';
            break;
        case FlashMessenger::NAMESPACE_DEFAULT:
            $aClasseCommune[2] = 'alert alert-warning alert-dismissible';
            break;
        case FlashMessenger::NAMESPACE_INFO:
            $aClasseCommune[2] = 'alert alert-info alert-dismissible';
            break;
        case FlashMessenger::NAMESPACE_SUCCESS:
            $aClasseCommune[2] = 'alert alert-success alert-dismissible';
            break;
        default:
            break;
    }
    echo $messenger->renderAllMessages($sNamespace, $aMessages, $aClasseCommune, true);
endforeach
?>

