<div class="page-title">
    <h4><?php echo $this->translate("Détail du raid") ?></h4>
</div>

    <section class="wrapper-bg col-md-8">
        <a  class='btn btn-success pull-right' href="<?php echo $this->url('front-raid-list', array('key' => $key)); ?>">
            <?php echo $this->translate("Retour à la liste des raids") ?>
        </a>
        <div>
            <h2> <?php echo $this->raid['note']; ?></h2>
            <i class="note"><?php echo sprintf($this->translate("En date du %s"), $raid['date']); ?>  </i>
        </div>
        <div>
            <h3><?php echo $this->translate("Liste des participants") ?> :</h3>
            <h4><?php echo $this->translate("Roster") ?></h4>
            <?php $bStart = true;?>
            <?php foreach ($this->participants as $participant) : ?>
                <?php if ($participant['roster']) : ?>
                    <?php if( $bStart == true): $bStart = false; else:?>
                     | 
                    <?php endif;?>
                <a class="char-name" href="<?php echo $this->url('front-personnage-detail', array('key' => $key,
                                                                                'idRaid' => $raid['idRaid'],
                                                                                'idPers' => $participant['idPersonnage'])); ?>"
                   style="color:<?php echo $participant['classe_couleur']; ?>" >
                        <?php echo ucfirst($participant['personnage_nom']); ?> 
                        <?php if($participant['ilvl']!== '0')echo "({$participant['ilvl']} ilvl) "; ?>
                        <?php if($participant['apply']):?>*<?php endif; ?>
                </a>
                <?php endif;?>
            <?php endforeach; ?>
            <p><i class="note"><?php echo $this->translate("* : est en apply") ?></i></p>
            <h4><?php echo $this->translate("Hors Roster") ?></h4>
            <?php $bStart = true;?>
            <?php foreach ($this->participants as $participant) : ?>
                <?php if ($participant['roster'] == 0): ?>
                    <?php if( $bStart == true): $bStart = false; else:?>
                     | 
                    <?php endif;?>
                     <a class="char-name" href="<?php echo $this->url('front-personnage-detail', array('key' => $key,
                                                    'idRaid' => $raid['idRaid'],
                                                    'idPers' => $participant['idPersonnage'])); ?>" 
                        style="color:<?php echo $participant['classe_couleur']; ?>" >
                            <?php echo ucfirst($participant['personnage_nom']); ?>

                        <?php if($participant['ilvl'] !== '0') echo "({$participant['ilvl']} ilvl) "; ?>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </section>
<aside class="list-loot col-md-4">
    <?php 
    $i = 1;
    $box = 1;
    foreach ($this->loots as $boss => $listLoot) : ?>
        <div class="loot col-md-4">
            <div class="panel-group">

                <div class="panel-head">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="<?php echo "#collapse".$box ;?>"><span class="glyphicon glyphicon-fire"></span> <?php echo ucwords($boss);?><span class="glyphicon glyphicon-collapse-down pull-right"</a>
                </h4>
                </div>
                <div id="<?php echo "collapse".$box ;?>" class="panel-collapse collapse"
                     <ul class="list-group">
                        <?php foreach($listLoot as $loot):?>
                            <p>
                                <img src='http://wow.zamimg.com/images/wow/icons/large/<?php echo $loot['icon']; ?>.jpg' height='25'/>
                                <a class="char-name" href='<?php echo str_replace('www','fr',$loot['wowHead']); ?>'>
                                    item
                                </a>

                                <label class="char-name" style="color:<?php if(isset($this->couleur[$loot['idPersonnage']])) echo $this->couleur[$loot['idPersonnage']]; ?>;" >
                                    <?php echo ucfirst($loot['nom_personnage']) ?>
                                </label> : <?php echo $loot['spe'] ?>
                            </p>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>

    <?php if( $i === 1): $i = 1;?>
    <div class='clearfix'></div>
    <?php else: $i++; 
          endif;
    ?>

    <?php 
        $box++;
        endforeach; 
    ?>

    <div class='clearfix'></div>

</aside>









