
<a href="<?php echo $this->url('front-roster-stat', array('key' => $key)); ?>" class="btn btn-success"><?php echo $this->translate("Statistiques Roster") ?></a>
<div class="block-area" id="defaultStyle">
    <table class="table table-bordered tile">
        <h3 class="block-title">Raids</h3>
    </table>
</div>

<script>
    $("#tableRaid").zfTable('<?php echo $this->url('front-raid-ajax-list', array('key' => $key)); ?>');
</script>
