
<div id="tableRaid">
    <table class="table table-striped">
        <thead>    <tr>
                <th>Id</th>
                <th>nom</th>
                <th>date</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($raids as $aRaid) { ?>
                <tr>
                    <td><?php echo $this->escapeHtml($aRaid['idRaid']); ?></td>
                    <td><?php echo $this->escapeHtml($aRaid['note']); ?></td>
                    <td><?php echo $this->escapeHtml($aRaid['date']); ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <div class="paging">

    </div>
</div>


