<?php echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5); ?>
<html lang="fr">
    <head>
        <?= $this->render('layout/app/head') ?>
    </head>
    <body>
        <div id="container">
            <?= $this->render('layout/app/messages') ?>
            <?= $this->render('layout/app/header_menu') ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2016 - <?php echo date('Y') ?> by Antarus - Capi  - Kadyll <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
