<?php echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5); ?>
<html lang="fr">
    <head>
        <?php echo $this->render('layout/app/head') ?>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-72079314-2', 'auto');
            ga('send', 'pageview');

        </script>
    </head>
    <body id="green-light">           
       <!--                Container                -->
       <div id="bloc_page">
            <header id="main-header">
                <!--                Header                   -->
                <?php echo $this->render('layout/app/header_menu') ?>  
            </header>
           
         
            <div class="content-wrapper">
                <section class="main-content">
                    <?php echo $this->render('layout/app/messages') ?>   
                    <?php echo $this->content; ?> 
                </section>
            </div>
        </div>
        <!--               Footer                   -->
        <footer class="main-footer-copy">
                <strong>&copy; 2016 - <?php echo date('Y') ?> by Antarus - Capi  - Kadyll</strong><i> - <?php echo $this->translate('All rights reserved.') ?></i>
                <div class="follow pull-right">
                    <a href='https://discord.gg/A3R2J' target="_blank"><img src='<?php echo $this->basePath("img/Discord-Logo-White") ; ?>' alt="logo-discord" style="width:20px;"/></a>
                    <a href="#"><img src="<?php echo $this->basePath("img/facebook.png"); ?>" alt='logo-facebook' style="width: 18px;"/></a>
                    <a href="https://twitter.com/RaidTracKer" target="_blank"><img src="<?php echo $this->basePath("img/twitter.png"); ?>" alt='logo-twitter' style="width: 20px;"/></a>
                </div>
        </footer>
        <!--            Control sidebar             -->
        <?php echo $this->render('layout/app/footer'); ?>
        <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
