<?php echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5); ?>
<html lang="fr">
    <head>
        <?php echo $this->render('layout/app/head') ?>
    </head>
    <body id="green-light">           
       <!--                Container                -->
       <div class="wrapper">
            <header id="main-header">
                <!--                Header                   -->
                <?php echo $this->render('layout/app/header_menu') ?>  
            </header>
            
         
            <div class="content-wrapper">
                <section class="main-content">
                    <?php echo $this->render('layout/app/messages') ?>   
                    <?php echo $this->content; ?> 
                </section>
            </div>
        </div>
        <!--               Footer                   -->
        <footer class="main-footer">
                <strong>&copy; 2016 - <?php echo date('Y') ?> by Antarus - Capi  - Kadyll</strong><i> - <?php echo $this->translate('All rights reserved.') ?></i>
        </footer>
        <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
