<a  class='btn btn-success pull-right' href="<?php echo $this->url('front-raid-list', array('key' => $key)); ?>">
    <?php echo $this->translate("Retour à la liste des raids") ?>
</a>
<div class="page-title">
    <h4><?php echo $this->translate("Stats du roster") . ' ' . ucfirst($stats['nom']) ?> </h4>
</div>    
<section class="content">   

    <section class="wrapper-bg col-md-8">
        <h4><?php echo $this->translate("Participation") ?> </h4>

        <?php echo isset($stats['participation']) ? '' : $this->translate("Aucun participant") ?>
        <?php foreach ($stats['participation'] as $participant) { ?>

            <section class="box stats col-md-4">
                <label> <?php echo ucfirst($participant['nom_personnage']) ?></label>
                <p><?php echo $this->translate("Nombre de raid") ?> :  <?php echo $participant['nbRaid'] ?></p>
                <p><?php echo $this->translate("Présence dans le pallier") ?> :  <?php echo $participant['presencePallier'] ?></p>
                <p><?php echo $this->translate("Présence global") ?> :  <?php echo $participant['presenceGlobal'] ?></p>
                <p><a href="<?php echo $this->url('front-personnage-stat', array('key' => $key, 'idPers' => $participant['idPersonnage'])); ?>"><?php echo $this->translate("- voir stats globales de se personnage -") ?></a></p>
                <!-- end for each -->
            </section>

        <?php } ?>
    </section>

    <aside class="col-md-4">
        <div class="box">
            <p> <label><?php echo $this->translate("Pallier configuré") ?>  </label>
                <?php if (!empty($this->palliers)): ?> 
                <ul>
                    <?php foreach ($this->palliers as $pallier) : ?>
                        <li><?php echo ucwords($pallier) ?> </li>
                    <?php endforeach; ?>
                </ul>
            <?php else: echo $this->translate("Pallier non configuré");
            endif; ?>
            </p>
            <p> 
                <label>
                <?php echo $this->translate("Nombre de raid dans les pallier configuré") ?>  
                </label> 
<?php echo isset($this->stats['nbTotalRaidPallier']) ? $this->stats['nbTotalRaidPallier'] : $this->translate("Pallier non configuré") ?>
            </p>
            <p>
                <label>
                <?php echo $this->translate("Nombre d'item dans les pallier configuré") ?>  
                </label> 
<?php echo isset($this->stats['nbItemPallier']) ? $this->stats['nbItemPallier'] : $this->translate("Pallier non configuré") ?>
            </p>
            <p>
                <label>
<?php echo $this->translate("Nombre de raid") ?>  
                </label>

<?php echo isset($this->stats['nbTotalRaid']) ? $this->stats['nbTotalRaid'] : '0'; ?>
            </p>
            <p>
                <label>
                <?php echo $this->translate("Nombre d'item") ?>  
                </label>
<?php echo isset($this->stats['nbItem']) ? $this->stats['nbItem'] : '0'; ?>
            </p>
        </div>
    </aside>

</section>

<div class="col-md-12">
<aside class="col-md-4">
    <ul>
        <li>
            <a class="btn btn-primary"  href="#presenceRaids">Présence Raids</a>
        </li>
        <li>
            <a class="btn btn-primary"   href="#lootsRaids">Loots Raids</a>
        </li>
        <li>
            <a class="btn btn-primary" href="#jesaispasquoimettre">Je sais pas quoi mettre</a>
        </li>
    </ul>
</aside>

<section class="col-md-8">
    <div id="presenceRaids" class="statsDiv" style="display: none;">
        <p>Test de présence</p>
    </div>
    <div id="lootsRaids" class="statsDiv" style="display: none;">
        <p>Test de loots</p>
    </div>
    <div id="jesaispasquoimettre" class="statsDiv" style="display: none;">
        <p>Je sais pas quoi mettre</p>
    </div>
</section>
</div>

<script src="//code.jquery.com/jquery-1.12.4.js"></script> 
<script src="//code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script> 
        var link = '';
        $( "a" ).on( "click", function()
        { 
            var newLink = $(this).attr('href');
            $( link).toggle( "drop", 500 );
            if( newLink !== link){
                $( newLink).toggle( "drop", 500 );    
                link = newLink;
            }
        });
</script>