<a href="<?php echo $this->url('front-raid-list', array('key' => $key)); ?>"><?php echo $this->translate("retour raid TODO use Nav") ?></a>
<div class="page-title">
    <h4><?php echo $this->translate("Stats du roster") . ' ' . ucfirst($stats['nom']) ?> </h4>
</div>
<section class="content">
    <section class="wrapper-bg col-md-8">
        <h4><?php echo $this->translate("Participation") ?> </h4>
        
            <?php echo isset($stats['participation']) ? '' : $this->translate("Aucun participant") ?>
            <?php foreach ($stats['participation'] as $participant) { ?>
                <section class="box stats col-md-4">
                    <label> <?php echo ucfirst($participant['nom_personnage']) ?></label>

                    <p><?php echo $this->translate("Nombre de raid") ?> :  <?php echo $participant['nbRaid'] ?></p>
                    <p><?php echo $this->translate("Présence dans le pallier") ?> :  <?php echo $participant['presencePallier'] ?></p>
                    <p><?php echo $this->translate("Présence global") ?> :  <?php echo $participant['presenceGlobal'] ?></p>
                    <p><a href="<?php echo $this->url('front-personnage-stat', array('key' => $key, 'idPers' => $participant['idPersonnage'])); ?>"><?php echo $this->translate("- voir stats globales de se personnage -") ?></a></p>
                <!-- end for each -->
                </section>
            <?php } ?>
        </section>
    <aside class="box col-md-4">
        <p> <label><?php echo $this->translate("Pallier configuré") ?>  </label>
            <?php if(!empty($this->palliers)): ?> 
            <ul>
            <?php foreach ($this->palliers as $pallier) : ?>
                <li><?php echo ucwords($pallier) ?> </li>
            <?php endforeach; ?>
            </ul>
            <?php else: echo $this->translate("Pallier non configuré"); endif; ?>
        </p>
        <p> 
            <label>
                <?php echo $this->translate("Nombre de raid dans les pallier configuré") ?>  
            </label> 
            <?php echo isset($this->stats['nbTotalRaidPallier']) ? $this->stats['nbTotalRaidPallier'] : $this->translate("Pallier non configuré") ?>
        </p>
        <p>
            <label>
                <?php echo $this->translate("Nombre d'item dans les pallier configuré") ?>  
            </label> 
            <?php echo isset($this->stats['nbItemPallier']) ? $this->stats['nbItemPallier'] : $this->translate("Pallier non configuré") ?>
        </p>
        <p>
            <label>
                <?php echo $this->translate("Nombre de raid") ?>  
            </label>

            <?php echo isset($this->stats['nbTotalRaid'])? $this->stats['nbTotalRaid']:'0';?>
        </p>
        <p>
            <label>
                <?php echo $this->translate("Nombre d'item") ?>  
            </label>
                <?php echo isset($this->stats['nbItem'])? $this->stats['nbItem']:'0'; ?>
        </p>
    </aside>
</section>