<b><?php echo $this->translate('Bienvenue sur Raid-TracKer,');?></b>
<?php echo $this->translate(' 
Pour activer votre compte, veuillez cliquer sur le lien ci dessous
ou copier/coller dans votre navigateur internet.');?>
 
<a href="http://local.raid-tracker.com<?php echo $this->url('validate-mail',array('key'=> $this->key)); ?>">http://www.raid-tracker.com<?php echo $this->url('validate-mail',array('key'=> $this->key)); ?></a>
 
<img src="http://dev.raid-tracker.com/img/Logotype-2.png" />
---------------
<?php echo $this->translate('Ceci est un mail automatique, Merci de ne pas y répondre');?>.