<b><?php echo $this->translate('Bienvenue sur Raid-TracKer,');?></b>
<?php echo $this->translate(' 
Pour activer votre compte, veuillez cliquer sur le lien ci dessous
ou copier/coller dans votre navigateur internet.');?>
 
<a href="http://<?php echo $this->urlProject; ?><?php echo $this->url('validate-mail',array('key'=> $this->key)); ?>">http://<?php echo $this->urlProject; ?><?php echo $this->url('validate-mail',array('key'=> $this->key)); ?></a>
 
<img src="http://<?php echo $this->urlProject; ?>/img/Logotype-2.png" />
---------------
<?php echo $this->translate('Ceci est un mail automatique, Merci de ne pas y répondre');?>.