<h1><?php echo $this->translate("Importer un personnage") ?></h1>

<form id="frmAjax" method='post' action="<?php echo $this->url('backend-personnages-importtraitement', array('id' => $this->id)) ?>" class="form-inline">
    <fieldset>
        <div class="control-group">
            <label class="control-label"><?php echo $this->translate("Nom") ?></label>
            <div class="controls">
                <input type='text' name="nom" required="true" value="<?php echo $perso['nom']; ?>"/>
            </div>
            <label class="control-label"><?php echo $this->translate("Serveur") ?></label>
            <div class="controls">
                <input type='text' name="serveur" required="true" value="<?php echo $perso['serveur']; ?>"/>
            </div>

            <div class="form-actions">
                <input id="submit" type='submit' value='submit' class="btn"/>
            </div>
            <div class="import">

            </div>
    </fieldset>
</form>

<?= $this->render('layout/backend/js-ajax-import') ?>