<h4>Articles :</h4>
<form class="form-inline" method="post" action="<?php echo $this->url('backend-pages', array('action' => 'articles')); ?>">
    <div class="form-group">
        <select name="articles" id="articles">            
            <?php foreach($this->listeArticles as $article): ?>
            <option value="<?php echo $article['idContent']; ?>"><?php echo $article['titleArticle'] ?></option>
            <?php endforeach; ?>
        </select>
        <button type="submit">Afficher</button>
    </div>
</form>

<p><?php echo sprintf($this->translate("Rédigé par %s, mis à jours le %s par %s "), $this->writeBy, $this->dateUpdate, $this->updateBy); ?></p>
<form method='post' action='<?php echo $this->url('backend-pages', array('action' => 'savearticle')); ?>'>
    <div class="form-group">
        <label>Titre*</label>
        <input type="text" name="title" value="<?php echo $this->titleArticle ; ?>" required/>
    </div>
    <textarea class="ckeditor" name="content"><?php echo $this->content; ?></textarea>
    <input type="hidden" name="idPages" value="<?php echo $this->idPages; ?>" />
    <input type="hidden" name="action" value="articles" />
    <p></p>
    <div class="form-group">
        <input type="submit" value="enregistrer" name="save"/>
        <input type="submit" value="effacer" name="delete"/>
    </div>
</form>