<h4>Articles :</h4>
<form class="form-inline" method="post" action="<?php echo $this->url('backend-pages', array('action' => 'articles')); ?>">
    <?php var_dump($this->listeArticles); ?>
    <div class="form-group">
        <select name="articles" id="articles">
            
            <?php foreach($this->listeArticles as $article): ?>
            <?php print_r($article); ?>
            <option value="<?php echo $article['idContent']; ?>"><?php echo $article['titleArticle'] ?></option>
            <?php endforeach; ?>
        </select>
        <button type="submit">Afficher</button>
    </div>
</form>

<p><?php echo sprintf($this->translate("Rédigé par %s, mis à jours le %s par %s "), $this->writeBy, $this->dateUpdate, $this->updateBy); ?></p>
<form method='post' action='<?php echo $this->url('backend-pages', array('action' => 'savepage')); ?>'>
    <textarea class="ckeditor" name="content"><?php echo $this->content; ?></textarea>
    <input type="hidden" name="idPages" value="<?php echo $this->idPages; ?>" />
    <input type="hidden" name="action" value="team" />
    <p></p>
    <input type="submit" value="enregistrer" />
</form>