<h1><?php echo $this->translate("Importer un item") ?></h1>

<form id="frmAjax" method='post' action="<?php echo $this->url('backend-items-import-traitement', array('id' => $this->id)) ?>" class="form-inline">
    <fieldset>
        <div class="control-group">
            <label class="control-label"><?php echo $this->translate("Id") ?></label>
            <div class="controls">
                <input type='text' name="id" required="true" value="<?php echo $item['id']; ?>"/>
            </div>
            <p class="help-block"><?php echo $this->translate("L'id correspond au lien utilisé par wowhead. le lien suivant http://www.wowhead.com/item=124159 .") ?></p>

            <div class="form-actions">
                <input id="submit" type='submit' value='submit' class="btn"/>
            </div>
            <div class="import">

            </div>
    </fieldset>
</form>

<?= $this->render('layout/backend/js-ajax-import') ?>