

<h1><?php echo $this->translate("Vous avez oublié votre mot de passe"); ?></h1>

<p><?php echo $this->translate("Entrez votre adresse email, nous allons vous aider à le réinitialiser."); ?></p>

<form action='<?php echo $this->url('forgetpass',array('action'=>'newpwdsave'))?>' method='post'>
    <p><?php echo $this->translate('Votre email :'); ?><input type='text' name='mail' value=''  /></p>
    <p><?php echo $this->translate('Nouveaux mot de passe :'); ?><input type='password' name='password' value=''  /></p>
    <p><?php echo $this->translate('Confirmation du mot de passe :'); ?><input type='password' name='passwordconfirm' value=''  /></p>
    <p><input type='hidden' name='key' value='<?php echo $this->key; ?>' /></p>
    <p><input type='submit' value='Enregistrement' /></p>
</form>