<a href="<?php echo $this->url('front-raid-detail', array('key' => $key, 'idRaid' => $idRaid)); ?>"><?php echo $this->translate("retour detail raid TODO use Nav") ?></a>

<p>
    <a href="<?php echo $this->url('front-personnage-stat', array('key' => $key, 'idPers' => $idPers)); ?>"><?php echo $this->translate("voir stats global de se personnage") ?></a>
</p>
<h1><?php echo $this->translate("Détail du raid pour le personnage") ?> </h1>
TODO voir controller Personnage action Detail

