<h1><?php echo $this->translate("Importer une zone") ?></h1>

<form id="frmAjax" method='post' action="<?php echo $this->url('backend-zone-import-traitement', array('id' => $this->id)) ?>" class="form-inline">
    <fieldset>
        <input type="hidden" name="id" required="true" value="" />
        <div class="control-group">
            <label class="control-label"><?php echo $this->translate("Id") ?></label>
            <div class="controls">
                <input type='text' name="idZone" required="true" value="<?php echo $zone['id']; ?>"/>
            </div>
            <p class="help-block"><?php echo $this->translate("L'id correspond au lien utilisé par wowhead. le lien suivant http://www.wowhead.com/zone=7545 correspond a la citadelle des flammes.") ?></p>
            <label class="control-label"><?php echo $this->translate("Importer les boss") ?></label>
            <div class="controls">
                <input type="radio" name="imp-boss" value="Oui" <?php if ($zone["imp-boss"] == 'Oui') echo 'checked'; ?>><?php echo $this->translate("Oui") ?>
                <input type="radio" name="imp-boss" value="Non" <?php if ($zone["imp-boss"] == 'Non') echo 'checked'; ?>><?php echo $this->translate("Non") ?>
            </div>

            <?= $this->render('layout/backend/locale') ?>

            <div class="form-actions">
                <input id="submit" type='submit' value='submit' class="btn"/>
            </div>
            <div class="import">

            </div>
    </fieldset>
</form>

<?= $this->render('layout/backend/js-ajax-import') ?>