<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfcUser\Form\RegisterFilter'=>__DIR__ . '/src/Zfcuser/Filter/RegisterFilter.php',
    'ZfcUser\Controller\UserController'=>__DIR__ . '/src/Zfcuser/Controller/UserController.php',
);