<h1><?php echo $this->translate("Importer un raid") ?></h1>

<form id="frmAjax" method='post' action="<?php echo $this->url('backend-raids-import-traitement', array('id' => $this->id)) ?>" class="form-inline">
    <fieldset>
        <div class="control-group">
            <label class="control-label"><?php echo $this->translate("Serveur") ?></label>
            <div class="controls">
                <input name="serveur" type="text" value="<?php echo $this->import['serveur'] ?>"  required="true"/>
            </div>
            <label class="control-label"><?php echo $this->translate("Nom du roster") ?></label>
            <div class="controls">
                <input name="nomRoster" type="text" value="<?php echo $this->import['nomRoster'] ?>"  required="true"/>
                <input type="hidden" name="idRoster"  value="<?php echo $this->import['idRoster']; ?>" />
            </div>
            <label class="control-label"><?php echo $this->translate("Xml eqdkp") ?></label>
            <div class="controls">
                <textarea name="txtImport" rows="10" cols="50" required="true"><?php echo $import['eqdkp'] ?></textarea>
            </div>

            <p class="help-block"><?php echo $this->translate("Import au format eqdkp") ?></p>
            <div class="form-actions">
                <input id="submit" type='submit' value='submit' class="btn"/>
            </div>
            <div class="import">

            </div>
    </fieldset>
</form>
<script type ="text/javascript">

    $(function () {
        autocompleteBase("input[name=nomRoster]", "input[name=idRoster]", "<?php echo $this->url('backend-roster-autocomplete', array('id' => $this->id)) ?>", "roster");
        gestionAjoutPersonnageRoster();

    });

</script>
<?= $this->render('layout/backend/js-ajax-import') ?>