<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Accueil\Controller\IndexController' => __DIR__ . '/src/Accueil/Controller/IndexController.php',
    'Accueil\Controller\ContactController' => __DIR__ . '/src/Accueil/Controller/ContactController.php',
    'Accueil\Controller\AproposController' => __DIR__ . '/src/Accueil/Controller/AproposController.php',
    'Accueil\Controller\DiscordbotController' => __DIR__ . '/src/Accueil/Controller/DiscordbotController.php',
    'Accueil\Controller\TeamController'        => __DIR__ . '/src/Accueil/Controller/TeamController.php',
    'Accueil\Module'                     => __DIR__ . '/Module.php',
    
);
