<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Accueil\Module' => __DIR__ . '/Module.php',
    'Accueil\Controller\IndexController' => __DIR__ . '/src/Accueil/Controller/IndexController.php',
);
