<div id="msgAjoutPersonnage"></div>
<form id="frmAjoutPersonnage" method='post' action="<?php echo $this->url('backend-roster-has-personnage-add', array('id' => $this->id)) ?>" class="form-inline">
    <fieldset>
        <div class="control-group">
            <label class="control-label"><?php echo $this->translate("Nom") ?></label>
            <div class="controls">
                <input type='text' name="nomPersonnage" required="true" value="<?php echo $player['nom']; ?>"/>
            </div>
            <input type="hidden" name="idPersonnage"  value="<?php echo $player['idPerso']; ?>" />
            <input type="hidden" name="idRoster" value="<?php echo $this->id; ?>" />
            <label class="control-label"><?php echo $this->translate("Role") ?></label>
            <div class="controls">
                <select class="form-control" name="idRole" required="true">
                    <?php if (!isset($player['roles'])) { ?>
                        <option value=""><?php echo $this->translate("--- Aucun Role de définit. ---"); ?></option>
                    <?php } else { ?>
                        <option value=""><?php echo $this->translate("--- Veuillez choisir ---"); ?></option>
                    <?php }
                    ?>
                    <?php foreach ($player['roles'] as $role) { ?>
                        <option value="<?php echo $role["idRole"]; ?>"><?php echo $role["nom"]; ?></option>
                        <?php
                    }
                    ?>

                </select>
            </div>
            <label class="control-label"><?php echo $this->translate("Est en apply") ?></label>
            <div class="controls">
                <input type='checkbox' name="isApply"  value="1"/>
            </div>
            <div class="form-actions">
                <input id="submit"  type="submit" value='Ajouter' class="btn" onclick=" vContinue = false;" />
                <input id="submitAndContinu"  type="submit" value='Ajouter et continuer' class="btn" onclick=" vContinue = true;" />
            </div>
    </fieldset>
</form>

<script type ="text/javascript">

    $(function () {
        autocompleteNomPersonnage("<?php echo $this->url('backend-personnage-autocomplete', array('id' => $this->id)) ?>");
        gestionAjoutPersonnageRoster();

    });

</script>
<?= $this->render('layout/backend/js-ajax-import') ?>