<div id="msgAjoutPersonnage"></div>
<form id="frmAjoutPersonnage" method='post' action="<?php echo $this->url('backend-roster-has-personnage-add', array('id' => $this->id)) ?>" class="form-inline">
    <fieldset>
        <div class="control-group">
            <label class="control-label"><?php echo $this->translate("Nom") ?></label>
            <div class="controls">
                <input type='text' name="nomPersonnage" required="true" value="<?php echo $player['nom']; ?>"/>
            </div>
            <input type="hidden" name="idPersonnage"  value="<?php echo $player['idPerso']; ?>" />
            <input type="hidden" name="idRoster" value="<?php echo $this->id; ?>" />
            <label class="control-label"><?php echo $this->translate("Role") ?></label>
            <div class="controls">
                <select class="form-control" name="idRole" required="true">
                    <?php if (!isset($player['roles'])) { ?>
                        <option value=""><?php echo $this->translate("--- Aucun Role de définit. ---"); ?></option>
                    <?php } else { ?>
                        <option value=""><?php echo $this->translate("--- Veuillez choisir ---"); ?></option>
                    <?php }
                    ?>
                    <?php foreach ($player['roles'] as $role) { ?>
                        <option value="<?php echo $role["idRole"]; ?>"><?php echo $role["nom"]; ?></option>
                        <?php
                    }
                    ?>

                </select>
            </div>
            <label class="control-label"><?php echo $this->translate("Est en apply") ?></label>
            <div class="controls">
                <input type='checkbox' name="isApply"  value="1"/>
            </div>
            <div class="form-actions">
                <input id="submit"  type="submit" value='Ajouter' class="btn" onclick=" vContinue = false;" />
                <input id="submitAndContinu"  type="submit" value='Ajouter et continuer' class="btn" onclick=" vContinue = true;" />
            </div>
    </fieldset>
</form>

<script type ="text/javascript">

    $(function () {
        $("input[name=nomPersonnage]").autocomplete({
            delay: 500,
            minLength: 3,
            source: function (request, response) {
                $.getJSON("<?php echo $this->url('backend-personnage-autocomplete', array('id' => $this->id)) ?>", {
// do not copy the api key; get your own at developer.rottentomatoes.com
                    rech: request.term,
                    page_limit: 10
                }, function (data) {
// data is an array of objects and must be transformed for autocomplete to use
                    var array = data.error ? [] : $.map(data.personnages, function (m) {
                        return {
                            id: m.idPersonnage,
                            nom: m.nom,
                            serveur: m.royaume,
                            guilde: m.guilde,
                            couleur: m.couleur
                        };
                    });
                    response(array);
                });
            },
            focus: function (event, ui) {
// prevent autocomplete from updating the textbox
                event.preventDefault();
            },
            select: function (event, ui) {
// prevent autocomplete from updating the textbox
                event.preventDefault();
// navigate to the selected item's url
// window.open(ui.item.url);
                $("input[name=nomPersonnage]").val(ui.item.nom);
                $("input[name=idPersonnage]").val(ui.item.id);

            }
        }).data("ui-autocomplete")._renderItem = function (ul, item) {
            var $a = $("<a></a>");
            if (item.guilde) {
                $("<span class='m-guilde'></span>").text(item.guilde).appendTo($a);
            }
            $("<span class='m-nom'></span>").css('color', item.couleur).text(item.nom).appendTo($a);
            $("<span class='m-separ'></span>").text(" - ").appendTo($a);
            $("<span class='m-serveur'></span>").text(item.serveur).appendTo($a);

            return $("<li></li>").append($a).appendTo(ul);
        };


// Lorsque je soumets le formulaire
        $('#frmAjoutPersonnage').on('submit', function (e) {
            e.preventDefault(); // J'empêche le comportement par défaut du navigateur, c-à-d de soumettre le formulaire

            var $this = $(this); // L'objet jQuery du formulaire

// Envoi de la requête HTTP en mode asynchrone
            $.ajax({
                url: $this.attr('action'), // Le nom du fichier indiqué dans le formulaire
                type: $this.attr('method'), // La méthode indiquée dans le formulaire (get ou post)
                data: $this.serialize(), // Je sérialise les données (j'envoie toutes les valeurs présentes dans le formulaire)
                dataType: 'json',
                beforeSend: function (html) { // Je récupère la réponse du fichier PHP

                },
                complete: function (html) { // Je récupère la réponse du fichier PHP

                    $("#msgAjoutPersonnage").removeClass('alert-success');
                    $("#msgAjoutPersonnage").removeClass('alert-danger');
                    if (html.responseJSON.error) {
                        $("#msgAjoutPersonnage").addClass('alert-danger').text(html.responseJSON.error.msg);
                    } else {
                        $("#msgAjoutPersonnage").addClass('alert-success').text(html.responseJSON.success.msg);
                        if (!vContinue) {
                            $("#popupGlobal").dialog("close");
                            majListe();
                        }
                    }
                }
            });
        });


    });

</script>
<?= $this->render('layout/backend/js-ajax-import') ?>